export const SET_FILE_NAME = "SET_FILE_NAME";
export const SET_FILE_TYPE = "SET_FILE_TYPE";
export const SET_VIDEO_FILE = "SET_VIDEO_FILE";
export const SET_VIDEO_TITLE = "SET_VIDEO_TITLE";
export const SET_VIDEO_DATE = "SET_VIDEO_DATE";
export const SET_VIDEO_TIME = "SET_VIDEO_TIME";
export const SET_VIDEO_LOCATION = "SET_VIDEO_LOCATION";
